version: '3.8'

services:
  proxysql:
    image: proxysql/proxysql:latest
    container_name: prod_env_proxysql
    restart: always
    environment:
      MYSQL_MASTER_HOST: ${MYSQL_MASTER_HOST}
      MYSQL_REPLICA_HOST: ${MYSQL_REPLICA_HOST}
      CA_PATH: ${CA_PATH}
      PROXYSQL_PORT: ${PROXYSQL_PORT}
      PROXYSQL_ADMIN_PORT: ${PROXY_ADMIN_PORT}
    ports:
      - ${PROXYSQL_PORT}:6033
      - ${PROXYSQL_ADMIN_PORT}:6032
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
      - ./configure.sql:/docker-entrypoint-initdb.d/configure.sql
    entrypoint: >
            sh -c "
            proxysql --config-file=/etc/proxysql.cnf &&
            mysql --user=admin --password=admin --host=127.0.0.1 --port=6032 < /docker-entrypoint-initdb.d/configure.sql
            "
